version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: edwix-postgres
    environment:
      POSTGRES_USER: edwix
      POSTGRES_PASSWORD: edwix_secret
      POSTGRES_DB: edwix
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U edwix' ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: edwix-redis
    ports:
      - '6380:6380'
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  redisdata:
